### ISSUE TITLE
INTENT_MESSAGE_PREFIX

### ISSUE THREAD

**Issue by PedroLopesG** [ac-voice-ai/rasa-audiocodes#5]
On rasa 2.x,  INTENT_MESSAGE_PREFIX  should be imported from rasa.shared.constants. Not from rasa.core.constants as it is.

**Comment by orgads** [comment]
Thanks for reporting! Care to open a PR? If you can't, I'll try to fix it on Sunday.

**Comment by orgads** [comment]
Fixed and published as 0.3.0.
