### ISSUE TITLE
Rasa-x

### ISSUE THREAD

**Issue by catiaAT** [ac-voice-ai/rasa-audiocodes#6]
Hi there!

Is it possible to run rasa_audiocodes with rasa-x with docker?
With rasa open source, I create a docker with a rasa volume and it works well, but in rasa-x, it keeps giving this error:

`RasaException: Failed to find input channel class for 'rasa_audiocodes.AudiocodesInput'. Unknown input channel. Check your credentials configuration to make sure the mentioned channel is not misspelled. If you are creating your own channel, make sure it is a proper name of a class in a module.
`

Do you have any clue?

Thanks!

**Comment by catiaAT** [comment]
Solved.

**Comment by orgads** [comment]
Care to share how?

**Comment by catiaAT** [comment]
> Care to share how?

Give me a couple of days, then i'll post here.
Right now, I'm really busy trying to deal with user inactivity. That is,  how to launch a message if the user is silent for x seconds. Can you give some advice? Thanks a lot.

**Comment by orgads** [comment]
Sure. You can configure:
```json
{
  "userNoInputTimeoutMS": 5000,
  "userNoInputSendEvent": true
}
```

Then handle the event in your actions script:
```python
  intent = tracker.latest_message['intent'].get('name')
  if intent == 'vaig_event_noUserInput':
      dispatcher.utter_message(text='Are you there?')
      return []
```

**Comment by catiaAT** [comment]
Hi orgads!

Nice to hear from you!
But, where do I configure this code?

```
{
  "userNoInputTimeoutMS": 5000,
  "userNoInputSendEvent": true
}
```


Thanks!

**Comment by orgads** [comment]
Assuming you refer to the cloud edition, you can do it in a message from the bot:

```python
dispatcher.utter_message(json_message={
    "type": "event",
    "name": "config",
    "sessionParams": {
        "userNoInputTimeoutMS": 5000,
        "userNoInputSendEvent": True
    }
})
```

**Comment by catiaAT** [comment]
Ok, I think I understood (yes it's the cloud edition).

It's kind of like this following action, where the call disconnects if the user has nothing more to say:

`
class ActionConnector(Action):
    def name(self) -> Text:
        return "action_connector"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        
        dispatcher.utter_message(response="utter_catia_adeus")
        #dispatcher.utter_message(text="Good bye!")
        dispatcher.utter_message(json_message={
            "type": "event",
            "name": "hangup",
            "activityParams": {
                "hangupReason": "conversationCompleted"
            }
        })`

**Comment by orgads** [comment]
Please refer to https://github.com/ac-voice-ai/bot-samples/tree/master/rasa for a sample bot.

**Comment by catiaAT** [comment]
Hi @orgads 

Sorry to bother ypu again.

I've seen the sample bot (it was from there that I created an "hangup action" to end the call when the user says "Bye", or something like that), but I still have some questions:

In which file do I put:
```
{
  "userNoInputTimeoutMS": 5000,
  "userNoInputSendEvent": true
}
```
and, how do I call / trigger the  intent "vaig_event_noUserInput" ?

> ```python
> if intent == 'vaig_event_noUserInput':
> ```

Hope you can help me, I'm stucked in this!

Thanks!

**Comment by orgads** [comment]
I added it to the sample bot as an optional feature (disabled by default).

I also updated the sample bot to Rasa 3.

**Comment by catiaAT** [comment]
Hi @orgads !

Thanks a lot for your help! It works like a charm!

I just had to change in the ActionConnector, where you had:

`name = metadata['callerDisplayName'] if metadata else ''`

to 

`name = metadata['caller'] if metadata else ''`

"callerDisplayName" was not one of metadata parameters.

**Comment by orgads** [comment]
Good to know, thanks. display name is optional indeed. I'll change it to fallback to caller.

This is just an example anyway, you can remove it if you don't need the caller details.
